name: mongo_document
description: The MongoDb Document Code Generator
version: 1.0.0
repository: https://github.com/wannclem/mongo_document_generator

environment:
  sdk: ^3.7.2

dependencies:
  build: ^2.4.0
  analyzer: ">=5.2.0 <7.0.0"
  source_gen: ^2.0.0
  mongo_document_annotation: 1.0.0
  mongo_dart: ^0.10.5
  json_annotation: ^4.9.0
  dart_style: ">=2.3.8 <4.0.0"
  path: ^1.9.1
  collection: ^1.19.1
  recase: ^4.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.0
  mockito: ^5.4.5
  build_test: ^2.2.3
