name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.9.0
  dotenv: ^4.2.0
  mongo_document_annotation: 1.0.0

dev_dependencies:
  build_runner: ^2.4.14
  freezed: ">=2.5.8 <4.0.0"
  json_serializable: ^6.9.3
  mongo_document: 1.0.0
  lints: ^5.0.0
  test: ^1.24.0
